media:
  - name: "uploads"
    label: "Media"
    input: "public/uploads"
    output: "/uploads"
    extensions:
      - ".jpg"
      - ".png"
      - ".jpeg"
      - ".mp4"

content:
  - name: "movies"
    label: "Movies"
    type: collection
    path: "src/content/movies"
    fields:
      - name: "id"
        label: "Internal ID"
        type: string
      - name: "title"
        label: "Title"
        type: string
      - name: "year"
        label: "Year"
        type: number
      - name: "genres"
        label: "Genres"
        type: array        # تم استبدال list بـ array
        of: string         # كل عنصر في المصفوفة نص
      - name: "thumbnail"
        label: "Thumbnail"
        type: image
      - name: "videoUrl"
        label: "Video URL"
        type: string
      - name: "description"
        label: "Description"
        type: text

  - name: "shows"
    label: "Shows"
    type: collection
    path: "src/content/shows"
    fields:
      - name: "id"
        label: "Internal ID"
        type: string
      - name: "title"
        label: "Title"
        type: string
      - name: "description"
        label: "Description"
        type: text
      - name: "thumbnail"
        label: "Thumbnail"
        type: image

  - name: "seasons"
    label: "Seasons"
    type: collection
    path: "src/content/shows/seasons"
    fields:
      - name: "id"
        label: "Internal ID"
        type: string
      - name: "title"
        label: "Title"
        type: string
      - name: "description"
        label: "Description"
        type: text
      - name: "thumbnail"
        label: "Thumbnail"
        type: image

  - name: "episodes"
    label: "Episodes"
    type: collection
    path: "src/content/shows/episodes"
    fields:
      - name: "id"
        label: "Internal ID"
        type: string
      - name: "title"
        label: "Title"
        type: string
      - name: "description"
        label: "Description"
        type: text
      - name: "videoUrl"
        label: "Video URL"
        type: string
      - name: "thumbnail"
        label: "Thumbnail"
        type: image
