media:
  - name: "uploads"
    label: "Media"
    input: "public/uploads"
    output: "/uploads"
    extensions:
      - ".jpg"
      - ".png"
      - ".jpeg"
      - ".mp4"

content:
  # ==================== Movies ====================
  - name: "movies"
    label: "Movies"
    type: collection
    path: "src/content/movies"
    fields:
      - name: "id"
        label: "Internal ID"
        type: string
      - name: "title"
        label: "Title"
        type: string
      - name: "year"
        label: "Year"
        type: number
      - name: "genres"
        label: "Genres"
        type: array
        of: string
      - name: "thumbnail"
        label: "Thumbnail"
        type: image
      - name: "videoUrl"
        label: "Video URL"
        type: string
      - name: "description"
        label: "Description"
        type: text

  # ==================== Shows ====================
  - name: "shows"
    label: "Shows"
    type: collection
    path: "src/content/shows"
    fields:
      - name: "id"
        label: "Internal ID"
        type: string
      - name: "title"
        label: "Title"
        type: string
      - name: "year"
        label: "Year"
        type: number
      - name: "description"
        label: "Description"
        type: text
      - name: "thumbnail"
        label: "Thumbnail"
        type: image

  # ==================== Seasons ====================
  - name: "seasons"
    label: "Seasons"
    type: collection
    path: "src/content/seasons"
    fields:
      - name: "id"
        label: "Season ID"
        type: string
      - name: "showId"
        label: "Parent Show ID"
        type: string
      - name: "title"
        label: "Title"
        type: string
      - name: "year"
        label: "Year"
        type: number
      - name: "description"
        label: "Description"
        type: text
      - name: "thumbnail"
        label: "Thumbnail"
        type: image

  # ==================== Episodes ====================
  - name: "episodes"
    label: "Episodes"
    type: collection
    path: "src/content/episodes"
    fields:
      - name: "id"
        label: "Internal ID"
        type: string
      - name: "showId"
        label: "Parent Show ID"
        type: string
      - name: "seasonEpisode"
        label: "Season & Episode"
        type: object
        fields:
          - name: "season"
            label: "الموسم"
            type: number
          - name: "episode"
            label: "الحلقة"
            type: number
      - name: "title"
        label: "Title"
        type: string
      - name: "year"
        label: "Year"
        type: number
      - name: "videoUrl"
        label: "Video URL"
        type: string
      - name: "description"
        label: "Description"
        type: text
      - name: "thumbnail"
        label: "Thumbnail"
        type: image
      - name: "type"
        label: "نوع الحلقة"
        type: select
        options:
          values:
            - value: "season"
              label: "الموسم"
            - value: "special"
              label: "عرض خاص / حلقة مميزة"
