media:
  - name: "uploads"
    label: "Media"
    input: "public/uploads"
    output: "/uploads"
    extensions:
      - ".jpg"
      - ".png"
      - ".jpeg"
      - ".mp4"

content:

  # ==================== Movies ====================
  - name: "movies"
    label: "Movies"
    type: collection
    path: "src/content/movies"
    fields:
      - name: id
        label: "رقم الفيلم"
        type: number
      - name: title
        label: "اسم الفيلم"
        type: string
      - name: thumbnail
        label: "بوستر الفيلم"
        type: image
      - name: description
        label: "وصف الفيلم"
        type: text
      - name: tags
        label: "الكلمات الدلالية"
        type: string
      - name: video
        label: "رابط الفيلم"
        type: object
        fields:
          - name: source_type
            label: "نوع المصدر"
            type: select
            options:
              values:
                - { value: "mp4", label: "MP4" }
                - { value: "embed", label: "Embed" }
          - name: source
            label: "الرابط"
            type: string

  # ==================== Shows ====================
  - name: "shows"
    label: "Shows"
    type: collection
    path: "src/content/shows"
    fields:
      - name: tv
        label: "رقم المسلسل"
        type: number
      - name: title
        label: "اسم المسلسل"
        type: string
      - name: description
        label: "الوصف"
        type: text
      - name: thumbnail
        label: "البوستر"
        type: image
      - name: year
        label: "سنة الإنتاج"
        type: number
      - name: draft
        label: "حالة"
        type: boolean
        default: false
      - name: tags
        label: "الكلمات الدلالية"
        type: string
      - name: meta_keywords
        label: "Meta Keywords"
        type: rich-text

  # ==================== Seasons ====================
  - name: "seasons"
    label: "Seasons"
    type: collection
    path: "src/content/seasons"
    fields:
      - name: tv
        label: "رقم المسلسل الأب"
        type: number
      - name: se
        label: "رقم الموسم"
        type: number

  # ==================== Episodes ====================
  - name: "episodes"
    label: "Episodes"
    type: collection
    path: "src/content/episodes"
    fields:
      - name: ep
        label: "رقم الحلقة"
        type: number
      - name: tv
        label: "رقم المسلسل الأب"
        type: number
      - name: se
        label: "رقم الموسم"
        type: number
      - name: title
        label: "عنوان الحلقة"
        type: string
      - name: duration
        label: "المدة"
        type: string
      - name: video
        label: "الفيديو"
        type: object
        fields:
          - name: source_type
            label: "نوع المصدر"
            type: select
            options:
              values:
                - { value: "mp4", label: "MP4" }
                - { value: "embed", label: "Embed" }
          - name: source
            label: "الرابط"
            type: string

  # ==================== Anime ====================
  - name: "anime"
    label: "Anime"
    type: collection
    path: "src/content/anime"
    fields:
      - name: tv
        label: "رقم الأنمي"
        type: number
      - name: title
        label: "اسم الأنمي"
        type: string
      - name: description
        label: "الوصف"
        type: text
      - name: thumbnail
        label: "البوستر"
        type: image
      - name: year
        label: "سنة الإنتاج"
        type: number
      - name: draft
        label: "حالة"
        type: boolean
        default: false
      - name: tags
        label: "الكلمات الدلالية"
        type: string
      - name: meta_keywords
        label: "Meta Keywords"
        type: rich-text

  # ==================== Anime Seasons ====================
  - name: "anime_seasons"
    label: "Anime Seasons"
    type: collection
    path: "src/content/anime/seasons"
    fields:
      - name: tv
        label: "رقم الأنمي الأب"
        type: number
      - name: se
        label: "رقم الموسم"
        type: number

  # ==================== Anime Episodes ====================
  - name: "anime_episodes"
    label: "Anime Episodes"
    type: collection
    path: "src/content/anime/episodes"
    fields:
      - name: ep
        label: "رقم الحلقة"
        type: number
      - name: tv
        label: "رقم الأنمي الأب"
        type: number
      - name: se
        label: "رقم الموسم"
        type: number
      - name: title
        label: "عنوان الحلقة"
        type: string
      - name: duration
        label: "المدة"
        type: string
      - name: video
        label: "الفيديو"
        type: object
        fields:
          - name: source_type
            label: "نوع المصدر"
            type: select
            options:
              values:
                - { value: "mp4", label: "MP4" }
                - { value: "embed", label: "Embed" }
          - name: source
            label: "الرابط"
            type: string
