media:
  - name: "uploads"
    label: "Media"
    input: "public/uploads"
    output: "/uploads"
    extensions:
      - ".jpg"
      - ".png"
      - ".jpeg"
      - ".mp4"

content:
  # ==================== Shows ====================
  - name: "shows"
    label: "Shows"
    type: collection
    path: "src/content/shows"
    fields:
      - name: title
        label: "اسم المسلسل"
        type: string
      - name: description
        label: "الوصف"
        type: text
      - name: subcategory
        label: "القسم الفرعي"
        type: select
        options:
          values:
            - { value: "افلام-عربية", label: "أفلام عربية" }
            - { value: "افلام-اجنبية", label: "أفلام اجنبية" }
      - name: thumbnail
        label: "البوستر"
        type: image
      - name: year
        label: "سنة الإنتاج"
        type: number
      - name: draft
        label: "حالة"
        type: boolean
        default: false
      - name: tags
        label: "الكلمات الدلالية"
        type: string
      - name: meta_keywords
        label: "Meta Keywords"
        type: rich-text

  # ==================== Seasons ====================
  - name: "seasons"
    label: "Seasons"
    type: collection
    path: "src/content/seasons"
    fields:
      - name: showId
        label: "المسلسل"
        type: select
        options:
          values: []  # ستملأ تلقائيًا من قائمة أسماء المسلسلات
      - name: seasonNumber
        label: "رقم الموسم"
        type: select
        options:
          values:
            - { value: 1, label: "الموسم 1" }
            - { value: 2, label: "الموسم 2" }
            - { value: 3, label: "الموسم 3" }
            - { value: 4, label: "الموسم 4" }
            - { value: 5, label: "الموسم 5" }
            - { value: 6, label: "الموسم 6" }
            - { value: 7, label: "الموسم 7" }
            - { value: 8, label: "الموسم 8" }
            - { value: 9, label: "الموسم 9" }
            - { value: 10, label: "الموسم 10" }
            - { value: 11, label: "الموسم 11" }
            - { value: 12, label: "الموسم 12" }
            - { value: 13, label: "الموسم 13" }
            - { value: 14, label: "الموسم 14" }
            - { value: 15, label: "الموسم 15" }
            - { value: 16, label: "الموسم 16" }
            - { value: 17, label: "الموسم 17" }
            - { value: 18, label: "الموسم 18" }
            - { value: 19, label: "الموسم 19" }
            - { value: 20, label: "الموسم 20" }

  # ==================== Episodes ====================
  - name: "episodes"
    label: "Episodes"
    type: collection
    path: "src/content/episodes"
    fields:
      - name: showId
        label: "المسلسل"
        type: select
        options:
          values: []  # ستملأ تلقائيًا من قائمة أسماء المسلسلات
      - name: showThumbnail
        label: "صورة المسلسل"
        type: image
        readonly: true  # يعرض البوستر تلقائيًا بدون الحاجة لإعادة رفعه
      - name: seasonEpisode
        label: "الموسم والحلقة"
        type: object
        fields:
          - name: season
            label: "الموسم"
            type: select
            options:
              values:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
                - 7
                - 8
                - 9
                - 10
          - name: episode
            label: "الحلقة"
            type: number
      - name: duration
        label: "المدة"
        type: string
      - name: video
        label: "الفيديو"
        type: object
        fields:
          - name: source_type
            label: "نوع المصدر"
            type: select
            options:
              values:
                - { value: "mp4", label: "MP4" }
                - { value: "embed", label: "Embed" }
          - name: source
            label: "الرابط"
            type: string
