media:
  - name: "uploads"
    label: "Media"
    type: "folder"
    path: "public/uploads"

collections:
  - name: "movies"
    label: "Movies"
    folder: "src/content/movies"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "id"
        label: "Internal ID"
        type: "string"
      - name: "slug"
        label: "Slug (URL)"
        type: "string"
      - name: "title"
        label: "Title"
        type: "string"
      - name: "year"
        label: "Year"
        type: "number"
      - name: "genres"
        label: "Genres"
        type: "list"
      - name: "thumbnail"
        label: "Thumbnail"
        type: "image"
      - name: "videoUrl"
        label: "Video URL"
        type: "string"
      - name: "description"
        label: "Description"
        type: "text"

  - name: "shows"
    label: "Shows"
    folder: "src/content/shows"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "id"
        label: "Internal ID"
        type: "string"
      - name: "slug"
        label: "Slug (URL)"
        type: "string"
      - name: "title"
        label: "Title"
        type: "string"
      - name: "description"
        label: "Description"
        type: "text"
      - name: "thumbnail"
        label: "Thumbnail"
        type: "image"

  - name: "seasons"
    label: "Seasons"
    folder: "src/conte
