media:
  - name: media
    label: "الوسائط"
    input: "content/media"
    output: "/media"
    extensions: [jpg, jpeg, png, mp4]

content:
  - name: movies
    label: "أفلام"
    type: collection
    path: "content/movies"
    view:
      fields:
        - images.poster
        - title
        - release_date
        - rating
        - subcategory
    fields:
      - name: title
        label: "العنوان"
        type: string
      - name: draft
        label: "حالة"
        type: boolean
        default: false
      - name: subcategory
        label: "القسم الفرعي"
        type: select
        options:
          values:
            - value: "افلام-عربية"
              label: "أفلام عربية"
            - value: "افلام-اجنبية"
              label: "أفلام اجنبية"
      - name: body
        label: "الوصف"
        type: rich-text
      - name: images
        label: "الصور"
        type: object
        fields:
          - name: poster
            label: "صورة الغلاف"
            type: image
            options:
              path: media
      - name: tags
        label: "الكلمات الدلالية"
        type: string
      - name: meta_keywords
        label: "Meta Keywords"
        type: string
      - name: video
        label: "الفيديو"
        type: object
        fields:
          - name: source_type
            label: "نوع المصدر"
            type: select
            options:
              values:
                - value: mp4
                  label: "MP4"
                - value: embed
                  label: "Embed"
          - name: source
            label: "الرابط"
            type: string
      - name: release_date
        label: "تاريخ الإصدار"
        type: string
      - name: duration
        label: "المدة"
        type: string
      - name: rating
        label: "التقييم"
        type: number

  - name: series
    label: "مسلسلات"
    type: collection
    path: "content/series"
    view:
      fields:
        - images.poster
        - title
        - release_date
        - rating
        - subcategory
    fields:
      - name: title
        label: "العنوان"
        type: string
      - name: draft
        label: "حالة"
        type: boolean
        default: false
      - name: subcategory
        label: "القسم الفرعي"
        type: select
        options:
          values:
            - value: "مسلسلات-عربية"
              label: "مسلسلات عربية"
            - value: "مسلسلات-اجنبية"
              label: "مسلسلات اجنبية"
      - name: body
        label: "الوصف"
        type: rich-text
      - name: images
        label: "الصور"
        type: object
        fields:
          - name: poster
            label: "صورة الغلاف"
            type: image
            options:
              path: media
      - name: tags
        label: "الكلمات الدلالية"
        type: string
      - name: meta_keywords
        label: "Meta Keywords"
        type: string
      - name: video
        label: "الفيديو"
        type: object
        fields:
          - name: source_type
            label: "نوع المصدر"
            type: select
            options:
              values:
                - value: mp4
                  label: "MP4"
                - value: embed
                  label: "Embed"
          - name: source
            label: "الرابط"
            type: string
      - name: series
        label: "معلومات المسلسل"
        type: object
        fields:
          - name: season
            label: "الموسم"
            type: number
          - name: episode
            label: "الحلقة"
            type: number
      - name: release_date
        label: "تاريخ الإصدار"
        type: string
      - name: duration
        label: "المدة"
        type: string
      - name: rating
        label: "التقييم"
        type: number

  - name: anime
    label: "انمى"
    type: collection
    path: "content/anime"
    view:
      fields:
        - images.poster
        - title
        - release_date
        - rating
    fields:
      - name: title
        label: "العنوان"
        type: string
      - name: draft
        label: "حالة"
        type: boolean
        default: false
      - name: body
        label: "الوصف"
        type: rich-text
      - name: images
        label: "الصور"
        type: object
        fields:
          - name: poster
            label: "صورة الغلاف"
            type: image
            options:
              path: media
      - name: tags
        label: "الكلمات الدلالية"
        type: string
      - name: meta_keywords
        label: "Meta Keywords"
        type: string
      - name: video
        label: "الفيديو"
        type: object
        fields:
          - name: source_type
            label: "نوع المصدر"
            type: select
            options:
              values:
                - value: mp4
                  label: "MP4"
                - value: embed
                  label: "Embed"
          - name: source
            label: "الرابط"
            type: string
      - name: release_date
        label: "تاريخ الإصدار"
        type: string
      - name: duration
        label: "المدة"
        type: string
      - name: rating
        label: "التقييم"
        type: number
